### ISSUE TITLE
現在好像不能用了，一直報錯

### ISSUE THREAD

**Issue by wuhaoyu010** [minibear2021/cn_bing_translator#1]
`import logging
import os

from cn_bing_translator import Translator

if __name__ == "__main__":
    logging.basicConfig(
        filename=os.path.join(os.getcwd(), 'demo.log'),
        level=logging.DEBUG,
        filemode='a',
        format='%(asctime)s - %(process)s - %(levelname)s: %(message)s')

    translator = Translator(logger=logging.getLogger("demo"))

    while 1:
        text = input("请输入待翻译文本：")
        if text == '0':
            break
        result = translator.process(text)
        print(result)`

Traceback (most recent call last):
  File "C:\Users\haoyu_wu\Desktop\Bing.py", line 21, in <module>
    result = translator.process(text)
  File "E:\Program Files (x86)\Python311\Lib\site-packages\cn_bing_translator\translator.py", line 97, in process
    raise UnknownStatusCode
cn_bing_translator.exceptions.UnknownStatusCode

**Comment by minibear2021** [comment]
应该是bing修改了页面结构，这个库属于实验性质，稳定使用还是调商用接口吧，暂时不准备更新了。
